In [1]:
import random
import sys
from dataclasses import dataclass, field
from typing import Optional
import torch
import argparse
import numpy as np
import pandas as pd

from processor import *

In [134]:
examples = SENDv1_Processor().get_train_examples("../../SENDv1-data/", sample_limit=10)

processing example = 0, video = ID156_vid2 ...


In [132]:
examples[0].visual_modality

tensor([[-1.1951, -1.1074, -0.5301,  ..., -2.3697, -1.4415, -1.7869],
        [-1.0872, -1.1141, -0.5604,  ..., -2.2777, -1.7785, -1.4546],
        [-0.6814, -0.8723, -0.2245,  ..., -1.0153, -1.0073, -0.1671],
        ...,
        [-0.6619, -0.6239, -0.5026,  ..., -0.4913, -1.3915, -0.4179],
        [-0.6859, -0.8065, -0.2771,  ..., -0.6026, -1.3562, -0.1435],
        [-0.6859, -0.8065, -0.2771,  ..., -0.6026, -1.3562, -0.1435]],
       dtype=torch.float64)

In [2]:
import cv2
import numpy as np
import os

In [3]:
# Playing video from file:
cap = cv2.VideoCapture('../../Sherine-Image/videos/Train/ID111_vid4_crop_downsized.mp4')

try:
    if not os.path.exists('data'):
        os.makedirs('data')
except OSError:
    print ('Error: Creating directory of data')

currentFrame = 0
while(True):
    # Capture frame-by-frame
    ret, frame = cap.read()
    print(frame)
    break
    
#     # Saves image of the current frame in jpg file
#     name = './data/frame' + str(currentFrame) + '.jpg'
#     print ('Creating...' + name)
#     cv2.imwrite(name, frame)

#     # To stop duplicate images
#     currentFrame += 1

# # When everything done, release the capture
# cap.release()
# cv2.destroyAllWindows()

[[[32 28 31]
  [32 28 31]
  [34 30 33]
  ...
  [27 27 25]
  [27 27 25]
  [27 27 25]]

 [[32 28 31]
  [32 28 31]
  [33 29 32]
  ...
  [27 27 25]
  [27 27 25]
  [27 27 25]]

 [[31 27 30]
  [31 27 30]
  [32 28 31]
  ...
  [27 27 25]
  [27 27 25]
  [27 27 25]]

 ...

 [[27 24 25]
  [27 24 25]
  [27 24 25]
  ...
  [18 15 16]
  [13 10 11]
  [10  7  8]]

 [[26 23 24]
  [26 23 24]
  [26 23 24]
  ...
  [18 15 16]
  [13 10 11]
  [10  7  8]]

 [[26 23 24]
  [26 23 24]
  [26 23 24]
  ...
  [18 15 16]
  [13 10 11]
  [10  7  8]]]


In [3]:
cap = cv2.VideoCapture('../../Sherine-Image/videos/Train/ID111_vid4_crop_downsized.mp4')


In [9]:
fps = cap.get(cv2.CAP_PROP_FPS)


In [10]:
fps

29.97002997002997

In [11]:
fps/1.5

19.98001998001998

In [13]:
1/fps

0.03336666666666667

In [17]:
0.03336666666666667*12

0.40040000000000003

In [3]:
from os import listdir
from os.path import isfile, join
mypath = "../../Sherine-Image/videos/Train/"
video_files_train = [(f.split("_")[0][2:]+"_"+f.split("_")[1][3:], f) for f in listdir(mypath) if isfile(join(mypath, f))]
mypath = "../../Sherine-Image/videos/Valid/"
video_files_dev = [(f.split("_")[0][2:]+"_"+f.split("_")[1][3:], f) for f in listdir(mypath) if isfile(join(mypath, f))]
mypath = "../../Sherine-Image/videos/Test/"
video_files_test = [(f.split("_")[0][2:]+"_"+f.split("_")[1][3:], f) for f in listdir(mypath) if isfile(join(mypath, f))]

In [4]:
train_map = [(f[0], "../../Sherine-Image/images/Train_resized/" +  f[1].split("_")[0]+"_"+f[1].split("_")[1]) for f in video_files_train]
dev_map = [(f[0], "../../Sherine-Image/images/Valid_resized/" +  f[1].split("_")[0]+"_"+f[1].split("_")[1]) for f in video_files_dev]
test_map = [(f[0], "../../Sherine-Image/images/Test_resized/" +  f[1].split("_")[0]+"_"+f[1].split("_")[1]) for f in video_files_test]

In [5]:
file_map = train_map + dev_map + test_map
file_map = dict(file_map)

In [6]:
mypath = "../../SENDv1-data/ratings/Train/observer_EWE/"
all_files_train = [f.split("_")[-2]+"_"+f.split("_")[-1].split(".")[0] for f in listdir(mypath) if isfile(join(mypath, f))]
mypath = "../../SENDv1-data/ratings/Valid/observer_EWE/"
all_files_dev = [f.split("_")[-2]+"_"+f.split("_")[-1].split(".")[0] for f in listdir(mypath) if isfile(join(mypath, f))]
mypath = "../../SENDv1-data/ratings/Test/observer_EWE/"
all_files_test = [f.split("_")[-2]+"_"+f.split("_")[-1].split(".")[0] for f in listdir(mypath) if isfile(join(mypath, f))]

In [7]:
partition = {
    "Train": all_files_train,
    "Valid": all_files_dev,
    "Test": all_files_test
}

In [8]:
import shutil
for k, v in partition.items():
    for f in partition[k]:
        p1 = f.split("_")[0]
        p2 = f.split("_")[1]
        file_n = f"ID{p1}_vid{p2}"
        file_n = f"../../SENDv1-data/features/{k}/image-raw/" + file_n
        destination = shutil.copytree(file_map[f], file_n)
        print(f"copying from {file_map[f]} to {file_n}")

copying from ../../Sherine-Image/images/Train_resized/ID120_vid4 to ../../SENDv1-data/features/Train/image-raw/ID120_vid4
copying from ../../Sherine-Image/images/Train_resized/ID178_vid1 to ../../SENDv1-data/features/Train/image-raw/ID178_vid1
copying from ../../Sherine-Image/images/Train_resized/ID147_vid3 to ../../SENDv1-data/features/Train/image-raw/ID147_vid3
copying from ../../Sherine-Image/images/Train_resized/ID163_vid2 to ../../SENDv1-data/features/Train/image-raw/ID163_vid2
copying from ../../Sherine-Image/images/Test_resized/ID147_vid2 to ../../SENDv1-data/features/Train/image-raw/ID147_vid2
copying from ../../Sherine-Image/images/Valid_resized/ID178_vid2 to ../../SENDv1-data/features/Train/image-raw/ID178_vid2
copying from ../../Sherine-Image/images/Test_resized/ID141_vid6 to ../../SENDv1-data/features/Train/image-raw/ID141_vid6
copying from ../../Sherine-Image/images/Train_resized/ID163_vid1 to ../../SENDv1-data/features/Train/image-raw/ID163_vid1
copying from ../../Sherine

copying from ../../Sherine-Image/images/Test_resized/ID171_vid1 to ../../SENDv1-data/features/Train/image-raw/ID171_vid1
copying from ../../Sherine-Image/images/Valid_resized/ID129_vid4 to ../../SENDv1-data/features/Train/image-raw/ID129_vid4
copying from ../../Sherine-Image/images/Train_resized/ID153_vid6 to ../../SENDv1-data/features/Train/image-raw/ID153_vid6
copying from ../../Sherine-Image/images/Train_resized/ID114_vid4 to ../../SENDv1-data/features/Train/image-raw/ID114_vid4
copying from ../../Sherine-Image/images/Train_resized/ID114_vid5 to ../../SENDv1-data/features/Train/image-raw/ID114_vid5
copying from ../../Sherine-Image/images/Train_resized/ID130_vid4 to ../../SENDv1-data/features/Train/image-raw/ID130_vid4
copying from ../../Sherine-Image/images/Valid_resized/ID129_vid5 to ../../SENDv1-data/features/Train/image-raw/ID129_vid5
copying from ../../Sherine-Image/images/Valid_resized/ID171_vid4 to ../../SENDv1-data/features/Train/image-raw/ID171_vid4
copying from ../../Sherin

copying from ../../Sherine-Image/images/Valid_resized/ID128_vid6 to ../../SENDv1-data/features/Valid/image-raw/ID128_vid6
copying from ../../Sherine-Image/images/Train_resized/ID137_vid1 to ../../SENDv1-data/features/Valid/image-raw/ID137_vid1
copying from ../../Sherine-Image/images/Train_resized/ID117_vid4 to ../../SENDv1-data/features/Valid/image-raw/ID117_vid4
copying from ../../Sherine-Image/images/Train_resized/ID115_vid6 to ../../SENDv1-data/features/Valid/image-raw/ID115_vid6
copying from ../../Sherine-Image/images/Train_resized/ID115_vid2 to ../../SENDv1-data/features/Valid/image-raw/ID115_vid2
copying from ../../Sherine-Image/images/Train_resized/ID131_vid3 to ../../SENDv1-data/features/Valid/image-raw/ID131_vid3
copying from ../../Sherine-Image/images/Test_resized/ID137_vid5 to ../../SENDv1-data/features/Valid/image-raw/ID137_vid5
copying from ../../Sherine-Image/images/Valid_resized/ID149_vid3 to ../../SENDv1-data/features/Valid/image-raw/ID149_vid3
copying from ../../Sherin

In [46]:
len(set(all_files).intersection(set(all_files_rating)))

193

In [80]:
file_map

{'142_3': '../../Sherine-Image/images/Train_resized/ID142_vid3',
 '130_4': '../../Sherine-Image/images/Train_resized/ID130_vid4',
 '153_4': '../../Sherine-Image/images/Train_resized/ID153_vid4',
 '179_4': '../../Sherine-Image/images/Train_resized/ID179_vid4',
 '156_6': '../../Sherine-Image/images/Train_resized/ID156_vid6',
 '163_5': '../../Sherine-Image/images/Train_resized/ID163_vid5',
 '114_4': '../../Sherine-Image/images/Train_resized/ID114_vid4',
 '123_5': '../../Sherine-Image/images/Train_resized/ID123_vid5',
 '129_2': '../../Sherine-Image/images/Train_resized/ID129_vid2',
 '120_3': '../../Sherine-Image/images/Train_resized/ID120_vid3',
 '173_4': '../../Sherine-Image/images/Train_resized/ID173_vid4',
 '117_2': '../../Sherine-Image/images/Train_resized/ID117_vid2',
 '131_1': '../../Sherine-Image/images/Train_resized/ID131_vid1',
 '181_6': '../../Sherine-Image/images/Train_resized/ID181_vid6',
 '117_1': '../../Sherine-Image/images/Train_resized/ID117_vid1',
 '118_1': '../../Sherine-